### PR TITLE
[Quant][Inductor] Prepack weight for conv and linear after quantization fusion

### PR DESCRIPTION
**Pull request by Xia-Weiwen**
**Summary**
Bug fix: Prepack weight and bias for conv and linear after quantization fusion. If we prepack weight and bias before fusion, we do not know if fusion would fail or not. If fusion does not work, prepacked weight and bias cannot be used by unfused ops.

**Test plan**
python test/test_quantization.py TestQuantizePT2EModels

---

@jgong5 @leslie-fang-intel Could you review? Thanks.

### CODE REVIEW

**Comment by leslie-fang-intel** [comment]
Another option is to keep the weight prepack at the original position and remove the `quant_per_channel` when we do the prepack.

**Comment by Xia-Weiwen** [comment]
> Another option is to keep the weight prepack at the original position and remove the `quant_per_channel` when we do the prepack. So the weight prepack can still benefits if the fusion failed.

Yes. That is better. I will update later. Thanks.

**Review by leslie-fang-intel — APPROVED** [review]

**Comment by leslie-fang-intel** [comment]
Looks good to me. I am thinking how can we add a testcase to ensure this case.

**Comment by leslie-fang-intel** [comment]
Oh,  another thing is since the passes are getting more and more. We had better add comments for the purpose of each case at the beginning of each pass.

**Comment by Xia-Weiwen** [comment]
Opened a new PR https://github.com/Xia-Weiwen/pytorch/pull/24

**Pull request closed without merging**
